server:
  port: 8087
zeebe:
  client:
    # cloud:
    #  clusterId:
    #  clientId:
    #  clientSecret:
    security:
      plaintext: true
    broker:
      gateway-address: 127.0.0.1:26500
    worker:
      defaultName: bpmnCinemaWorker
      threads: 3
cinema.payment.service.error: false